Repository abs0lut3pwn4g3/RTB-CTF-Framework, pull requests merged in 2020-03, with the labels that each got.

#24 Added travis integration
  .travis.yml
Labels: gssoc20, medium

#30 Moving organisation details to footer
  src/FlaskRTBCTF/static/main.css
  src/FlaskRTBCTF/templates/layout.html
Labels: easy, gssoc20

#32 Added ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: documentation, easy, gssoc20
