Repository abs0lut3pwn4g3/RTB-CTF-Framework, pull requests merged in 2020-04, with the labels that each got.

#42 Update Readme
  README.md
Labels: PR: reviewed-approved, easy, gssoc20

#44 Travis testing/linting Patch
  .travis.yml
  setup.cfg
Labels: PR: unreviewed

#46 Badges for this project resolved - 2
  README.md
Labels: PR: unreviewed

#45 Badges for this project resolved - 1
  README.md
Labels: PR: unreviewed

#48 Changed path of pull_request_template.md
  .github/pull_request_template.md
Labels: PR: unreviewed

#43 Adding Machine model
  src/FlaskRTBCTF/__init__.py
  src/FlaskRTBCTF/config.py
  src/FlaskRTBCTF/ctf/routes.py
  src/FlaskRTBCTF/models.py
  src/FlaskRTBCTF/templates/machine.html
  src/FlaskRTBCTF/users/routes.py
  src/create_db.py
  src/run.py
Labels: PR: reviewed-approved, gssoc20, hard

#49 Merge gssoc20-dev into master
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/pull_request_template.md
  .lgtm.yml
  .pylintrc
  .travis.yml
  README.md
  setup.cfg
  src/FlaskRTBCTF/__init__.py
  src/FlaskRTBCTF/config.py
  src/FlaskRTBCTF/ctf/routes.py
  src/FlaskRTBCTF/models.py
  src/FlaskRTBCTF/templates/machine.html
  src/FlaskRTBCTF/users/routes.py
  src/FlaskRTBCTF/users/utils.py
  src/create_db.py
  src/requirements.txt
  src/run.py
Labels: PR: unreviewed

#50 merge gssoc20-dev into master
  .lgtm.yml
  .pylintrc
  .travis.yml
  README.md
  src/FlaskRTBCTF/__init__.py
  src/FlaskRTBCTF/admin/views.py
  src/FlaskRTBCTF/config.py
  src/FlaskRTBCTF/ctf/forms.py
  src/FlaskRTBCTF/ctf/routes.py
  src/FlaskRTBCTF/main/routes.py
  src/FlaskRTBCTF/models.py
  src/FlaskRTBCTF/users/forms.py
  src/FlaskRTBCTF/users/routes.py
  src/FlaskRTBCTF/users/utils.py
  src/create_db.py
  src/requirements.txt
  src/run.py
Labels: PR: unreviewed

#51 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: PR: reviewed-approved

#52 Introduced psf/black formatting
  .travis.yml
  CONTRIBUTING.md
  README.md
  app.json
  setup.cfg
  src/FlaskRTBCTF/__init__.py
  src/FlaskRTBCTF/admin/views.py
  src/FlaskRTBCTF/config.py
  src/FlaskRTBCTF/ctf/forms.py
  src/FlaskRTBCTF/ctf/routes.py
  src/FlaskRTBCTF/helpers.py
  src/FlaskRTBCTF/main/routes.py
  src/FlaskRTBCTF/models.py
  src/FlaskRTBCTF/users/forms.py
  src/FlaskRTBCTF/users/routes.py
  src/FlaskRTBCTF/users/utils.py
  src/create_db.py
  src/requirements.txt
  src/run.py
Labels: PR: partially-approved

#53 merge gssoc20-dev into master
  .travis.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  app.json
  setup.cfg
  src/FlaskRTBCTF/__init__.py
  src/FlaskRTBCTF/admin/views.py
  src/FlaskRTBCTF/config.py
  src/FlaskRTBCTF/ctf/forms.py
  src/FlaskRTBCTF/ctf/routes.py
  src/FlaskRTBCTF/helpers.py
  src/FlaskRTBCTF/main/routes.py
  src/FlaskRTBCTF/models.py
  src/FlaskRTBCTF/users/forms.py
  src/FlaskRTBCTF/users/routes.py
  src/FlaskRTBCTF/users/utils.py
  src/create_db.py
  src/requirements.txt
  src/run.py
Labels: PR: reviewed-approved

#54 merge into master
  CONTRIBUTING.md
  INSTALLATION.md
  README.md
  app.json
  runtime.txt
  src/FlaskRTBCTF/helpers.py
  src/FlaskRTBCTF/models.py
  src/FlaskRTBCTF/users/forms.py
Labels: PR: unreviewed

#59 merge "challenges-dev" into "gssoc20-dev"
  .travis.yml
  CONTRIBUTING.md
  Dockerfile
  README.md
  app.json
  docker-compose.yml
  rtb_nginx_http
  screenshots/home_ss.png
  screenshots/machine_ss.png
  screenshots/scoreboard_ss.png
  src/FlaskRTBCTF/.gitignore
  src/FlaskRTBCTF/__init__.py
  src/FlaskRTBCTF/admin/views.py
  src/FlaskRTBCTF/config.py
  src/FlaskRTBCTF/ctf/forms.py
  src/FlaskRTBCTF/ctf/models.py
  src/FlaskRTBCTF/ctf/routes.py
  src/FlaskRTBCTF/helpers.py
  src/FlaskRTBCTF/main/forms.py
  src/FlaskRTBCTF/main/models.py
  src/FlaskRTBCTF/main/routes.py
  src/FlaskRTBCTF/models.py
  src/FlaskRTBCTF/static/main.css
  src/FlaskRTBCTF/static/main.js
  src/FlaskRTBCTF/templates/account.html
  src/FlaskRTBCTF/templates/challenges.html
  src/FlaskRTBCTF/templates/forms.html
  src/FlaskRTBCTF/templates/home.html
  src/FlaskRTBCTF/templates/layout.html
  src/FlaskRTBCTF/templates/login.html
  src/FlaskRTBCTF/templates/machine.html
  src/FlaskRTBCTF/templates/machines.html
  src/FlaskRTBCTF/templates/macros.html
  src/FlaskRTBCTF/templates/new_machine.html
  src/FlaskRTBCTF/templates/notifications.html
  src/FlaskRTBCTF/templates/register.html
  src/FlaskRTBCTF/templates/scoreboard.html
  src/FlaskRTBCTF/templates/setup.html
  src/FlaskRTBCTF/users/forms.py
  src/FlaskRTBCTF/users/models.py
  src/FlaskRTBCTF/users/routes.py
  src/FlaskRTBCTF/utils/__init__.py
  src/FlaskRTBCTF/utils/admin_manager.py
  src/FlaskRTBCTF/utils/bcrypt.py
  src/FlaskRTBCTF/utils/cache.py
  src/FlaskRTBCTF/utils/helpers.py
  src/FlaskRTBCTF/utils/login_manager.py
  src/FlaskRTBCTF/utils/mail.py
  src/FlaskRTBCTF/utils/models.py
  src/create_db.py
  src/create_db.test.py
  src/docker-entrypoint.sh
  src/requirements.txt
Labels: PR: unreviewed

#58 Adding UserMachineModel
  CONTRIBUTING.md
  src/FlaskRTBCTF/ctf/models.py
  src/FlaskRTBCTF/ctf/routes.py
Labels: PR: unreviewed, gssoc20, hard
